- table: component_type
  schema: reference
- table: operations_type
  schema: reference
- table: soil_type
  schema: reference
- table: vehicle_type
  schema: reference
- table: other
  dummy: True
  schema: reference
  children:
    - table: ports
      bool:
        - jacking_capability
      geo:
        - point_location
    - table: component
      children:
        - table: component_shared
          join: fk_component_id
        - table: component_discrete
          join: fk_component_id
          children:
            - table: component_anchor
              join: fk_component_discrete_id
              fkeys:
                fk_component_type_id: reference.component_type
            - table: component_collection_point
              join: fk_component_discrete_id
              fkeys:
                fk_component_type_id: reference.component_type
              array:
                - foundation_locations
                - centre_of_gravity
            - table: component_connector
              join: fk_component_discrete_id
              fkeys:
                fk_component_type_id: reference.component_type
            - table: component_mooring_discrete
              join: fk_component_discrete_id
              fkeys:
                fk_component_type_id: reference.component_type
            - table: component_transformer
              join: fk_component_discrete_id
              fkeys:
                fk_component_type_id: reference.component_type
        - table: component_continuous
          join: fk_component_id
          children:
            - table: component_cable
              join: fk_component_continuous_id
              fkeys:
                fk_component_type_id: reference.component_type
            - table: component_mooring_continuous
              join: fk_component_continuous_id
              fkeys:
                fk_component_type_id: reference.component_type
            - table: component_pile
              join: fk_component_continuous_id
              fkeys:
                fk_component_type_id: reference.component_type
            - table: component_rope
              join: fk_component_continuous_id
              fkeys:
                fk_component_type_id: reference.component_type
              array:
                - rope_stiffness_curve
    - table: constants
      dummy: True
      children:
        - table: constants
          pkey: lock
        - table: ref_current_drag_coef_rect
          pkey: width_length
        - table: ref_drag_coef_cyl
          pkey: reynolds_number
        - table: ref_drift_coef_float_rect
          pkey: wavenumber_draft
        - table: ref_holding_capacity_factors_plate_anchors
          pkey: relative_embedment_depth
        - table: ref_line_bcf
          pkey: soil_friction_angle
        - table: ref_pile_deflection_coefficients
          pkey: depth_coefficient
        - table: ref_pile_limiting_values_noncalcareous
          pkey: soil_friction_angle
        - table: ref_pile_moment_coefficient_sam
          pkey: depth_coefficient
        - table: ref_pile_moment_coefficient_sbm
          pkey: depth_coefficient
        - table: ref_rectangular_wave_inertia
          pkey: width/length
        - table: ref_subgrade_reaction_coefficient_cohesionless
          pkey: allowable_deflection_diameter
        - table: ref_subgrade_reaction_coefficient_k1_cohesive
          pkey: allowable_deflection_diameter
        - table: ref_superline_nylon
          pkey: extension
        - table: ref_superline_polyester
          pkey: extension
        - table: ref_superline_steelite
          pkey: extension
        - table: ref_wake_amplification_factor_cyl
          pkey: kc_steady_drag_coefficient
        - table: ref_wind_drag_coef_rect
          pkey: width_length
        - table: soil_type_geotechnical_properties
          pkey: fk_soil_type_id
          fkeys:
            fk_soil_type_id: reference.soil_type
    - table: equipment
      dummy: True
      children:
        - table: equipment_cable_burial
          bool:
            - jetting_capability
            - ploughing_capability
            - cutting_capability
        - table: equipment_divers
        - table: equipment_drilling_rigs
        - table: equipment_excavating
        - table: equipment_hammer
        - table: equipment_mattress
        - table: equipment_rock_filter_bags
        - table: equipment_rov
        - table: equipment_soil_lay_rates
          pkey: equipment_type
        - table: equipment_soil_penet_rates
          pkey: equipment_type
        - table: equipment_split_pipe
        - table: equipment_vibro_driver
    - table: operations
      dummy: True
      children:
        - table: operations_limit_hs
          fkeys:
            fk_operations_id: reference.operations_type
        - table: operations_limit_tp
          fkeys:
            fk_operations_id: reference.operations_type
        - table: operations_limit_ws
          fkeys:
            fk_operations_id: reference.operations_type
        - table: operations_limit_cs
          fkeys:
            fk_operations_id: reference.operations_type
    - table: vehicle
      children:
        - table: vehicle_shared
          join: fk_vehicle_id
        - table: vehicle_helicopter
          join: fk_vehicle_id
          fkeys:
            fk_vehicle_type_id: reference.vehicle_type
        - table : vehicle_vessel_anchor_handling
          join: fk_vehicle_id
          fkeys:
            fk_vehicle_type_id: reference.vehicle_type
        - table: vehicle_vessel_cable_laying
          join: fk_vehicle_id
          fkeys:
            fk_vehicle_type_id: reference.vehicle_type
          bool:
            - cable_splice_capabilities
            - dynamic_positioning_capabilities 
        - table: vehicle_vessel_cargo
          join: fk_vehicle_id
          fkeys:
            fk_vehicle_type_id: reference.vehicle_type
          bool:
            - dynamic_positioning_capabilities
        - table: vehicle_vessel_jackup
          join: fk_vehicle_id
          fkeys:
            fk_vehicle_type_id: reference.vehicle_type
          bool:
            - dynamic_positioning_capabilities
        - table: vehicle_vessel_tugboat
          join: fk_vehicle_id
          fkeys:
            fk_vehicle_type_id: reference.vehicle_type
- table: device
  autokey: True
  schema: project
  children:
    - table: device_shared
      array:
        - centre_of_gravity
        - foundation_locations
        - footprint_corner_coords
        - variable_power_factor
      bool:
        - two_stage_assembly
      join: fk_device_id
      stripf: True
    - table: device_floating
      array:
        - maximum_displacement
        - fairlead_locations
        - umbilical_connection_point
      bool:
        - depth_variation_permitted
      join: fk_device_id
      stripf: True
    - table: device_tidal
      bool:
        - two_ways_flow
      join: fk_device_id
      stripf: True
    - table: device_tidal_power_performance
      join: fk_device_id
      stripf: True
    - table: device_wave
      join: fk_device_id
      stripf: True
    - table: sub_systems
      join: fk_device_id
      stripf: True
      children:
        - table: sub_systems_access
          join: fk_sub_system_id
        - table: sub_systems_economic
          join: fk_sub_system_id
        - table: sub_systems_inspection
          join: fk_sub_system_id
        - table: sub_systems_install
          join: fk_sub_system_id
        - table: sub_systems_maintenance
          join: fk_sub_system_id
          bool:
            - interruptible
        - table: sub_systems_operation_weightings
          join: fk_sub_system_id
        - table: sub_systems_replace
          join: fk_sub_system_id
          bool:
            - interruptible
- table: site
  autokey: True
  geo:
    - site_boundary
    - lease_boundary
    - corridor_boundary
    - cable_landing_location
  schema: project
  children:
    - table: cable_corridor_constraint
      join: fk_site_id
      stripf: True
    - table: time_series_energy_wave
      join: fk_site_id
      time:
        - measure_time
      date:
        - measure_date
      stripf: True
    - table: time_series_om_tidal
      join: fk_site_id
      time:
        - measure_time
      date:
        - measure_date
      stripf: True
    - table: time_series_om_wave
      join: fk_site_id
      time:
        - measure_time
      date:
        - measure_date
      stripf: True
    - table: time_series_om_wind
      join: fk_site_id
      time:
        - measure_time
      date:
        - measure_date
      stripf: True
    - table: constraint
      join: fk_site_id
      geo:
        - boundary
      stripf: True
    - table: lease_area
      join: fk_site_id
      geo:
        - tidal_occurrence_point
      bool:
        - has_helipad
      stripf: True
    - table: cable_corridor_bathymetry
      join: fk_site_id
      geo:
        - utm_point
      stripf: True
      children:
        - table: cable_corridor_bathymetry_layer
          join: fk_bathymetry_id
          fkeys:
            fk_soil_type_id: reference.soil_type
    - table: bathymetry
      join: fk_site_id
      geo:
        - utm_point
      stripf: True
      children: 
        - table: bathymetry_layer
          join: fk_bathymetry_id
          fkeys:
            fk_soil_type_id: reference.soil_type
        - table: time_series_energy_tidal
          join: fk_bathymetry_id
          time:
            - measure_time
          date:
            - measure_date
