[tool.poetry]
name = "dtocean-logistics"
version = "3.0.1"
description = "Logistics functions for the DTOcean installation and maintenance modules"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
