[project]
name = "dtocean-qt"
version = "0.10.1"
description = "Qt extensions for the DTOcean GUI"
authors = [
    {name = "Mathew Topper",email = "damm_horse@yahoo.co.uk"}
]
readme = "README.md"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "chardet (>=5.2.0,<6.0.0)",
    "pyside6 (>=6.9.0,<7.0.0)",
    "easygui (>=0.98.3,<0.99.0)"
]

[project.urls]
Homepage = "https://github.com/DTOcean/dtocean"
Issues = "https://github.com/DTOcean/dtocean/issues"

[tool.poetry]
packages = [{include = "dtocean_qt", from = "src"}]

[tool.poetry.build]
script = "scripts/build-icons.py"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-qt = "^4.4.0"
pytest-cov = "^6.0.0"
pytest-env = "^1.1.5"

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.396"
deptry = "^0.21.1"
pandas-stubs = "^2.2.3.241126"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '=='

[tool.pyright]
typeCheckingMode = "basic"

[tool.pytest.ini_options]
filterwarnings = [
    'ignore:Failed to disconnect *:RuntimeWarning',
]

[tool.pytest_env]
QT_DEBUG_PLUGINS = 1

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "pyside6"]
build-backend = "poetry.core.masonry.api"
