# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\high\about.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName(_fromUtf8("AboutDialog"))
        AboutDialog.resize(500, 504)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(500, 0))
        AboutDialog.setMaximumSize(QtCore.QSize(500, 16777215))
        AboutDialog.setAutoFillBackground(False)
        AboutDialog.setStyleSheet(_fromUtf8(""))
        self.verticalLayout_2 = QtGui.QVBoxLayout(AboutDialog)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrollArea = QtGui.QScrollArea(AboutDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 481, 952))
        self.scrollAreaWidgetContents.setStyleSheet(_fromUtf8("background: white;"))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.logoLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.logoLabel.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.logoLabel.setText(_fromUtf8(""))
        self.logoLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/logos/dtocean2plus._padded.png")))
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName(_fromUtf8("logoLabel"))
        self.verticalLayout_3.addWidget(self.logoLabel)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.versionLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.versionLabel.setFont(font)
        self.versionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.versionLabel.setObjectName(_fromUtf8("versionLabel"))
        self.verticalLayout_3.addWidget(self.versionLabel)
        self.longLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.longLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.longLabel.setObjectName(_fromUtf8("longLabel"))
        self.verticalLayout_3.addWidget(self.longLabel)
        spacerItem2 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.line_1 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.verticalLayout_3.addWidget(self.line_1)
        self.DOGIntroLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.DOGIntroLabel.setStyleSheet(_fromUtf8("QMenu::item{\n"
"  background-color: rgb(255, 255, 255);\n"
"  color:  rgb(0, 0, 0);\n"
" }\n"
"QMenu::item:selected{\n"
"  background-color: rgb(252, 124, 1);\n"
"  color:  rgb(0, 0, 0);\n"
"}"))
        self.DOGIntroLabel.setOpenExternalLinks(True)
        self.DOGIntroLabel.setObjectName(_fromUtf8("DOGIntroLabel"))
        self.verticalLayout_3.addWidget(self.DOGIntroLabel)
        spacerItem3 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.DOGlogoLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.DOGlogoLabel.setText(_fromUtf8(""))
        self.DOGlogoLabel.setPixmap(QtGui.QPixmap(_fromUtf8(":/logos/dog_logo_wide_300.png")))
        self.DOGlogoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DOGlogoLabel.setObjectName(_fromUtf8("DOGlogoLabel"))
        self.verticalLayout_3.addWidget(self.DOGlogoLabel)
        self.supportLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.supportLabel.setStyleSheet(_fromUtf8("QMenu::item{\n"
"  background-color: rgb(255, 255, 255);\n"
"  color:  rgb(0, 0, 0);\n"
" }\n"
"QMenu::item:selected{\n"
"  background-color: rgb(252, 124, 1);\n"
"  color:  rgb(0, 0, 0);\n"
"}"))
        self.supportLabel.setWordWrap(True)
        self.supportLabel.setOpenExternalLinks(True)
        self.supportLabel.setObjectName(_fromUtf8("supportLabel"))
        self.verticalLayout_3.addWidget(self.supportLabel)
        spacerItem4 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_3.addWidget(self.line_2)
        self.peopleIntroLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.peopleIntroLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.peopleIntroLabel.setIndent(-1)
        self.peopleIntroLabel.setObjectName(_fromUtf8("peopleIntroLabel"))
        self.verticalLayout_3.addWidget(self.peopleIntroLabel)
        self.peopleLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.peopleLabel.setStyleSheet(_fromUtf8("padding: 10px"))
        self.peopleLabel.setWordWrap(True)
        self.peopleLabel.setObjectName(_fromUtf8("peopleLabel"))
        self.verticalLayout_3.addWidget(self.peopleLabel)
        spacerItem5 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.insitutionIntroLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.insitutionIntroLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.insitutionIntroLabel.setObjectName(_fromUtf8("insitutionIntroLabel"))
        self.verticalLayout_3.addWidget(self.insitutionIntroLabel)
        spacerItem6 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(300, 150))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.institutionLabel = QtGui.QLabel(self.frame)
        self.institutionLabel.setMinimumSize(QtCore.QSize(300, 150))
        self.institutionLabel.setText(_fromUtf8(""))
        self.institutionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.institutionLabel.setObjectName(_fromUtf8("institutionLabel"))
        self.verticalLayout_4.addWidget(self.institutionLabel)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem7 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.line_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.DTOceanPlusLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.DTOceanPlusLabel.setStyleSheet(_fromUtf8("QMenu::item{\n"
"  background-color: rgb(255, 255, 255);\n"
"  color:  rgb(0, 0, 0);\n"
" }\n"
"QMenu::item:selected{\n"
"  background-color: rgb(252, 124, 1);\n"
"  color:  rgb(0, 0, 0);\n"
"}"))
        self.DTOceanPlusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.DTOceanPlusLabel.setOpenExternalLinks(True)
        self.DTOceanPlusLabel.setObjectName(_fromUtf8("DTOceanPlusLabel"))
        self.verticalLayout_3.addWidget(self.DTOceanPlusLabel)
        spacerItem8 = QtGui.QSpacerItem(20, 2, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.line_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_3.addWidget(self.line_4)
        self.freeSoftwareLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.freeSoftwareLabel.setFont(font)
        self.freeSoftwareLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.freeSoftwareLabel.setObjectName(_fromUtf8("freeSoftwareLabel"))
        self.verticalLayout_3.addWidget(self.freeSoftwareLabel)
        self.copyrightLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.copyrightLabel.setTextFormat(QtCore.Qt.RichText)
        self.copyrightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.copyrightLabel.setObjectName(_fromUtf8("copyrightLabel"))
        self.verticalLayout_3.addWidget(self.copyrightLabel)
        self.GPLLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.GPLLabel.setStyleSheet(_fromUtf8("QMenu::item{\n"
"  background-color: rgb(255, 255, 255);\n"
"  color:  rgb(0, 0, 0);\n"
" }\n"
"QMenu::item:selected{\n"
"  background-color: rgb(252, 124, 1);\n"
"  color:  rgb(0, 0, 0);\n"
"}"))
        self.GPLLabel.setTextFormat(QtCore.Qt.RichText)
        self.GPLLabel.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.GPLLabel.setOpenExternalLinks(True)
        self.GPLLabel.setObjectName(_fromUtf8("GPLLabel"))
        self.verticalLayout_3.addWidget(self.GPLLabel)
        self.iconsLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.iconsLabel.setFont(font)
        self.iconsLabel.setMidLineWidth(-4)
        self.iconsLabel.setTextFormat(QtCore.Qt.RichText)
        self.iconsLabel.setWordWrap(True)
        self.iconsLabel.setObjectName(_fromUtf8("iconsLabel"))
        self.verticalLayout_3.addWidget(self.iconsLabel)
        self.line_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_3.addWidget(self.line_5)
        self.softwareLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.softwareLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.softwareLabel.setObjectName(_fromUtf8("softwareLabel"))
        self.verticalLayout_3.addWidget(self.softwareLabel)
        self.packagesLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.packagesLabel.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.packagesLabel.setWordWrap(True)
        self.packagesLabel.setObjectName(_fromUtf8("packagesLabel"))
        self.verticalLayout_3.addWidget(self.packagesLabel)
        self.logoLabel.raise_()
        self.versionLabel.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.peopleIntroLabel.raise_()
        self.freeSoftwareLabel.raise_()
        self.peopleLabel.raise_()
        self.GPLLabel.raise_()
        self.line_1.raise_()
        self.copyrightLabel.raise_()
        self.line_5.raise_()
        self.softwareLabel.raise_()
        self.packagesLabel.raise_()
        self.iconsLabel.raise_()
        self.longLabel.raise_()
        self.DOGlogoLabel.raise_()
        self.supportLabel.raise_()
        self.insitutionIntroLabel.raise_()
        self.DOGIntroLabel.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.DTOceanPlusLabel.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About", None))
        self.versionLabel.setText(_translate("AboutDialog", "DTOcean Version", None))
        self.longLabel.setText(_translate("AboutDialog", "Optimal Design Tools for Ocean Energy Arrays", None))
        self.DOGIntroLabel.setText(_translate("AboutDialog", "DTOcean is maintained by Mathew Topper @ <a href=\'http://www.dataonlygreater.com/\'>Data Only Greater</a>:", None))
        self.supportLabel.setText(_translate("AboutDialog", "For free community support please go to <a href=\'https://github.com/dtocean/dtocean\'>github.com/DTOcean</a>. For training and consultation services see <a href=\'http://www.dataonlygreater.com/\'>dataonlygreater.com</a>.", None))
        self.peopleIntroLabel.setText(_translate("AboutDialog", "Thanks are given to the following people for their help with this release:", None))
        self.peopleLabel.setText(_translate("AboutDialog", "People Label", None))
        self.insitutionIntroLabel.setText(_translate("AboutDialog", "The following insitutions support the development of DTOcean:", None))
        self.DTOceanPlusLabel.setText(_translate("AboutDialog", "<p>The DTOceanPlus project aims to expand and improve the capabilities of DTOcean<p>\n"
"<p> For further details and latest news see <a href=\'https://www.dtoceanplus.eu\'>www.dtoceanplus.eu</a>", None))
        self.freeSoftwareLabel.setText(_translate("AboutDialog", "DTOcean is free software", None))
        self.copyrightLabel.setText(_translate("AboutDialog", "Copyright &copy; The DTOcean Developers", None))
        self.GPLLabel.setText(_translate("AboutDialog", "<html><head/><body><p><a href=\"https://www.gnu.org/licenses/gpl.html\"><span style=\" text-decoration: underline; color:#0000ff;\">GNU General Public License</span></a></p></body></html>", None))
        self.iconsLabel.setText(_translate("AboutDialog", "The icons used in DTOcean are adapted from the Crystal Clear icon set (&copy; Everaldo Coelho), the GNOME Desktop Tango icon set (&copy; GNOME icon artists) and the ScreenRuler Tango icon (&copy; Jaanos) ", None))
        self.softwareLabel.setText(_translate("AboutDialog", "Python 2.7, Qt 4.8.7, PyQt 4.11.4", None))
        self.packagesLabel.setText(_translate("AboutDialog", "Please see the individual DTOcean packages for further details regarding module dependencies and licensing", None))

import resources_about_rc
