# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\shared\advancedposition.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AdvancedPositionWidget(object):
    def setupUi(self, AdvancedPositionWidget):
        AdvancedPositionWidget.setObjectName(_fromUtf8("AdvancedPositionWidget"))
        AdvancedPositionWidget.resize(673, 786)
        self.verticalLayout = QtGui.QVBoxLayout(AdvancedPositionWidget)
        self.verticalLayout.setMargin(2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(AdvancedPositionWidget)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_config = QtGui.QWidget()
        self.tab_config.setAutoFillBackground(True)
        self.tab_config.setObjectName(_fromUtf8("tab_config"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.tab_config)
        self.horizontalLayout_12.setContentsMargins(9, 9, -1, -1)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.frame_3 = QtGui.QFrame(self.tab_config)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.fileBox = QtGui.QGroupBox(self.frame_3)
        self.fileBox.setObjectName(_fromUtf8("fileBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.fileBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.importConfigButton = QtGui.QPushButton(self.fileBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importConfigButton.sizePolicy().hasHeightForWidth())
        self.importConfigButton.setSizePolicy(sizePolicy)
        self.importConfigButton.setAutoDefault(False)
        self.importConfigButton.setObjectName(_fromUtf8("importConfigButton"))
        self.verticalLayout_3.addWidget(self.importConfigButton)
        self.exportConfigButton = QtGui.QPushButton(self.fileBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportConfigButton.sizePolicy().hasHeightForWidth())
        self.exportConfigButton.setSizePolicy(sizePolicy)
        self.exportConfigButton.setAutoDefault(False)
        self.exportConfigButton.setObjectName(_fromUtf8("exportConfigButton"))
        self.verticalLayout_3.addWidget(self.exportConfigButton)
        spacerItem = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.fileBox)
        self.statusBox = QtGui.QGroupBox(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBox.sizePolicy().hasHeightForWidth())
        self.statusBox.setSizePolicy(sizePolicy)
        self.statusBox.setObjectName(_fromUtf8("statusBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.statusBox)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.statusLabel = QtGui.QLabel(self.statusBox)
        self.statusLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statusLabel.setWordWrap(True)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.verticalLayout_2.addWidget(self.statusLabel)
        self.horizontalLayout.addWidget(self.statusBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.workDirBox = QtGui.QGroupBox(self.frame_3)
        self.workDirBox.setFlat(False)
        self.workDirBox.setObjectName(_fromUtf8("workDirBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.workDirBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.workDirLabel = QtGui.QLabel(self.workDirBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workDirLabel.sizePolicy().hasHeightForWidth())
        self.workDirLabel.setSizePolicy(sizePolicy)
        self.workDirLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.workDirLabel.setObjectName(_fromUtf8("workDirLabel"))
        self.horizontalLayout_2.addWidget(self.workDirLabel)
        self.workDirLineEdit = QtGui.QLineEdit(self.workDirBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.workDirLineEdit.sizePolicy().hasHeightForWidth())
        self.workDirLineEdit.setSizePolicy(sizePolicy)
        self.workDirLineEdit.setObjectName(_fromUtf8("workDirLineEdit"))
        self.horizontalLayout_2.addWidget(self.workDirLineEdit)
        self.workDirToolButton = QtGui.QToolButton(self.workDirBox)
        self.workDirToolButton.setObjectName(_fromUtf8("workDirToolButton"))
        self.horizontalLayout_2.addWidget(self.workDirToolButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.cleanDirCheckBox = QtGui.QCheckBox(self.workDirBox)
        self.cleanDirCheckBox.setObjectName(_fromUtf8("cleanDirCheckBox"))
        self.verticalLayout_4.addWidget(self.cleanDirCheckBox)
        self.verticalLayout_7.addWidget(self.workDirBox)
        spacerItem1 = QtGui.QSpacerItem(17, 602, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_12.addWidget(self.frame_3)
        spacerItem2 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.horizontalLayout_12.setStretch(0, 1)
        self.frame_3.raise_()
        self.tabWidget.addTab(self.tab_config, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setAutoFillBackground(True)
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_settings)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.settingsFrame = QtGui.QFrame(self.tab_settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFrame.sizePolicy().hasHeightForWidth())
        self.settingsFrame.setSizePolicy(sizePolicy)
        self.settingsFrame.setMaximumSize(QtCore.QSize(500, 16777215))
        self.settingsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.settingsFrame.setObjectName(_fromUtf8("settingsFrame"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.settingsFrame)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.objectiveBox = QtGui.QGroupBox(self.settingsFrame)
        self.objectiveBox.setObjectName(_fromUtf8("objectiveBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.objectiveBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.costVarLabel = QtGui.QLabel(self.objectiveBox)
        self.costVarLabel.setMinimumSize(QtCore.QSize(110, 0))
        self.costVarLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.costVarLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.costVarLabel.setObjectName(_fromUtf8("costVarLabel"))
        self.gridLayout_3.addWidget(self.costVarLabel, 0, 0, 1, 1)
        self.costVarLayout = QtGui.QHBoxLayout()
        self.costVarLayout.setObjectName(_fromUtf8("costVarLayout"))
        self.gridLayout_3.addLayout(self.costVarLayout, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.costVarCheckBox = QtGui.QCheckBox(self.objectiveBox)
        self.costVarCheckBox.setObjectName(_fromUtf8("costVarCheckBox"))
        self.gridLayout_3.addWidget(self.costVarCheckBox, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.penaltyLabel = QtGui.QLabel(self.objectiveBox)
        self.penaltyLabel.setMinimumSize(QtCore.QSize(110, 0))
        self.penaltyLabel.setObjectName(_fromUtf8("penaltyLabel"))
        self.horizontalLayout_5.addWidget(self.penaltyLabel)
        self.penaltyLayout = QtGui.QHBoxLayout()
        self.penaltyLayout.setObjectName(_fromUtf8("penaltyLayout"))
        self.horizontalLayout_5.addLayout(self.penaltyLayout)
        self.penaltyUnitsLabel = QtGui.QLabel(self.objectiveBox)
        self.penaltyUnitsLabel.setObjectName(_fromUtf8("penaltyUnitsLabel"))
        self.horizontalLayout_5.addWidget(self.penaltyUnitsLabel)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.toleranceLabel = QtGui.QLabel(self.objectiveBox)
        self.toleranceLabel.setMinimumSize(QtCore.QSize(110, 0))
        self.toleranceLabel.setObjectName(_fromUtf8("toleranceLabel"))
        self.horizontalLayout_18.addWidget(self.toleranceLabel)
        self.toleranceLayout = QtGui.QHBoxLayout()
        self.toleranceLayout.setObjectName(_fromUtf8("toleranceLayout"))
        self.horizontalLayout_18.addLayout(self.toleranceLayout)
        self.toleranceUnitsLabel = QtGui.QLabel(self.objectiveBox)
        self.toleranceUnitsLabel.setObjectName(_fromUtf8("toleranceUnitsLabel"))
        self.horizontalLayout_18.addWidget(self.toleranceUnitsLabel)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_18)
        self.verticalLayout_17.addWidget(self.objectiveBox)
        self.computeBox = QtGui.QGroupBox(self.settingsFrame)
        self.computeBox.setObjectName(_fromUtf8("computeBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.computeBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.nThreadLabel = QtGui.QLabel(self.computeBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nThreadLabel.sizePolicy().hasHeightForWidth())
        self.nThreadLabel.setSizePolicy(sizePolicy)
        self.nThreadLabel.setMinimumSize(QtCore.QSize(102, 0))
        self.nThreadLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nThreadLabel.setObjectName(_fromUtf8("nThreadLabel"))
        self.horizontalLayout_3.addWidget(self.nThreadLabel)
        self.nThreadSpinBox = QtGui.QSpinBox(self.computeBox)
        self.nThreadSpinBox.setMinimum(1)
        self.nThreadSpinBox.setMaximum(999)
        self.nThreadSpinBox.setProperty("value", 1)
        self.nThreadSpinBox.setObjectName(_fromUtf8("nThreadSpinBox"))
        self.horizontalLayout_3.addWidget(self.nThreadSpinBox)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.threadInfoLabel = QtGui.QLabel(self.computeBox)
        self.threadInfoLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.threadInfoLabel.setObjectName(_fromUtf8("threadInfoLabel"))
        self.horizontalLayout_3.addWidget(self.threadInfoLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.abortXLabel = QtGui.QLabel(self.computeBox)
        self.abortXLabel.setObjectName(_fromUtf8("abortXLabel"))
        self.horizontalLayout_6.addWidget(self.abortXLabel)
        self.abortXSpinBox = QtGui.QSpinBox(self.computeBox)
        self.abortXSpinBox.setMaximum(999)
        self.abortXSpinBox.setObjectName(_fromUtf8("abortXSpinBox"))
        self.horizontalLayout_6.addWidget(self.abortXSpinBox)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.abortXInfoabel = QtGui.QLabel(self.computeBox)
        self.abortXInfoabel.setObjectName(_fromUtf8("abortXInfoabel"))
        self.horizontalLayout_6.addWidget(self.abortXInfoabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.abortTimeLabel = QtGui.QLabel(self.computeBox)
        self.abortTimeLabel.setObjectName(_fromUtf8("abortTimeLabel"))
        self.horizontalLayout_16.addWidget(self.abortTimeLabel)
        self.abortTimeSpinBox = QtGui.QSpinBox(self.computeBox)
        self.abortTimeSpinBox.setMaximum(9999999)
        self.abortTimeSpinBox.setObjectName(_fromUtf8("abortTimeSpinBox"))
        self.horizontalLayout_16.addWidget(self.abortTimeSpinBox)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem9)
        self.abortTimeInfoabel = QtGui.QLabel(self.computeBox)
        self.abortTimeInfoabel.setObjectName(_fromUtf8("abortTimeInfoabel"))
        self.horizontalLayout_16.addWidget(self.abortTimeInfoabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.verticalLayout_17.addWidget(self.computeBox)
        self.advancedBox = QtGui.QGroupBox(self.settingsFrame)
        self.advancedBox.setObjectName(_fromUtf8("advancedBox"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.advancedBox)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.minNoiseLabel = QtGui.QLabel(self.advancedBox)
        self.minNoiseLabel.setObjectName(_fromUtf8("minNoiseLabel"))
        self.horizontalLayout_23.addWidget(self.minNoiseLabel)
        self.minNoiseSpinBox = QtGui.QSpinBox(self.advancedBox)
        self.minNoiseSpinBox.setEnabled(False)
        self.minNoiseSpinBox.setMinimum(1)
        self.minNoiseSpinBox.setMaximum(999)
        self.minNoiseSpinBox.setObjectName(_fromUtf8("minNoiseSpinBox"))
        self.horizontalLayout_23.addWidget(self.minNoiseSpinBox)
        self.minNoiseCheckBox = QtGui.QCheckBox(self.advancedBox)
        self.minNoiseCheckBox.setChecked(True)
        self.minNoiseCheckBox.setObjectName(_fromUtf8("minNoiseCheckBox"))
        self.horizontalLayout_23.addWidget(self.minNoiseCheckBox)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem10)
        self.verticalLayout_16.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.maxNoiseLabel = QtGui.QLabel(self.advancedBox)
        self.maxNoiseLabel.setObjectName(_fromUtf8("maxNoiseLabel"))
        self.horizontalLayout_24.addWidget(self.maxNoiseLabel)
        self.maxNoiseSpinBox = QtGui.QSpinBox(self.advancedBox)
        self.maxNoiseSpinBox.setEnabled(True)
        self.maxNoiseSpinBox.setMinimum(1)
        self.maxNoiseSpinBox.setMaximum(999)
        self.maxNoiseSpinBox.setProperty("value", 128)
        self.maxNoiseSpinBox.setObjectName(_fromUtf8("maxNoiseSpinBox"))
        self.horizontalLayout_24.addWidget(self.maxNoiseSpinBox)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.populationLabel = QtGui.QLabel(self.advancedBox)
        self.populationLabel.setObjectName(_fromUtf8("populationLabel"))
        self.horizontalLayout_20.addWidget(self.populationLabel)
        self.populationSpinBox = QtGui.QSpinBox(self.advancedBox)
        self.populationSpinBox.setEnabled(False)
        self.populationSpinBox.setMinimum(1)
        self.populationSpinBox.setMaximum(999)
        self.populationSpinBox.setObjectName(_fromUtf8("populationSpinBox"))
        self.horizontalLayout_20.addWidget(self.populationSpinBox)
        self.populationCheckBox = QtGui.QCheckBox(self.advancedBox)
        self.populationCheckBox.setChecked(True)
        self.populationCheckBox.setObjectName(_fromUtf8("populationCheckBox"))
        self.horizontalLayout_20.addWidget(self.populationCheckBox)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem12)
        self.verticalLayout_16.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.maxResamplesLabel1 = QtGui.QLabel(self.advancedBox)
        self.maxResamplesLabel1.setObjectName(_fromUtf8("maxResamplesLabel1"))
        self.horizontalLayout_25.addWidget(self.maxResamplesLabel1)
        self.maxResamplesComboBox = QtGui.QComboBox(self.advancedBox)
        self.maxResamplesComboBox.setObjectName(_fromUtf8("maxResamplesComboBox"))
        self.maxResamplesComboBox.addItem(_fromUtf8(""))
        self.maxResamplesComboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_25.addWidget(self.maxResamplesComboBox)
        self.maxResamplesLabel2 = QtGui.QLabel(self.advancedBox)
        self.maxResamplesLabel2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.maxResamplesLabel2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxResamplesLabel2.setObjectName(_fromUtf8("maxResamplesLabel2"))
        self.horizontalLayout_25.addWidget(self.maxResamplesLabel2)
        self.maxResamplesSpinBox = QtGui.QSpinBox(self.advancedBox)
        self.maxResamplesSpinBox.setMinimum(1)
        self.maxResamplesSpinBox.setMaximum(999)
        self.maxResamplesSpinBox.setProperty("value", 2)
        self.maxResamplesSpinBox.setObjectName(_fromUtf8("maxResamplesSpinBox"))
        self.horizontalLayout_25.addWidget(self.maxResamplesSpinBox)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem13)
        self.verticalLayout_16.addLayout(self.horizontalLayout_25)
        self.verticalLayout_17.addWidget(self.advancedBox)
        spacerItem14 = QtGui.QSpacerItem(20, 415, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem14)
        self.horizontalLayout_4.addWidget(self.settingsFrame)
        spacerItem15 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.horizontalLayout_4.setStretch(0, 1)
        self.tabWidget.addTab(self.tab_settings, _fromUtf8(""))
        self.tab_params = QtGui.QWidget()
        self.tab_params.setAutoFillBackground(True)
        self.tab_params.setObjectName(_fromUtf8("tab_params"))
        self.verticalLayout_29 = QtGui.QVBoxLayout(self.tab_params)
        self.verticalLayout_29.setMargin(0)
        self.verticalLayout_29.setObjectName(_fromUtf8("verticalLayout_29"))
        self.scrollArea = QtGui.QScrollArea(self.tab_params)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 663, 756))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_31.setMargin(0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.paramsFrame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.paramsFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.paramsFrame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.paramsFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.paramsFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.paramsFrame.setObjectName(_fromUtf8("paramsFrame"))
        self.paramsFrameLayout = QtGui.QVBoxLayout(self.paramsFrame)
        self.paramsFrameLayout.setObjectName(_fromUtf8("paramsFrameLayout"))
        self.horizontalLayout_31.addWidget(self.paramsFrame)
        spacerItem16 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem16)
        self.horizontalLayout_31.setStretch(0, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_29.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_params, _fromUtf8(""))
        self.tab_results = QtGui.QWidget()
        self.tab_results.setAutoFillBackground(True)
        self.tab_results.setObjectName(_fromUtf8("tab_results"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_results)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.inspectBox = QtGui.QGroupBox(self.tab_results)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inspectBox.sizePolicy().hasHeightForWidth())
        self.inspectBox.setSizePolicy(sizePolicy)
        self.inspectBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.inspectBox.setObjectName(_fromUtf8("inspectBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.inspectBox)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.inspectLabel = QtGui.QLabel(self.inspectBox)
        self.inspectLabel.setObjectName(_fromUtf8("inspectLabel"))
        self.horizontalLayout_10.addWidget(self.inspectLabel)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.deleteSimsBox = QtGui.QCheckBox(self.inspectBox)
        self.deleteSimsBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.deleteSimsBox.setChecked(True)
        self.deleteSimsBox.setObjectName(_fromUtf8("deleteSimsBox"))
        self.gridLayout_4.addWidget(self.deleteSimsBox, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.bestSimButton = QtGui.QRadioButton(self.inspectBox)
        self.bestSimButton.setObjectName(_fromUtf8("bestSimButton"))
        self.simButtonGroup = QtGui.QButtonGroup(AdvancedPositionWidget)
        self.simButtonGroup.setObjectName(_fromUtf8("simButtonGroup"))
        self.simButtonGroup.addButton(self.bestSimButton)
        self.horizontalLayout_9.addWidget(self.bestSimButton)
        self.worstSimButton = QtGui.QRadioButton(self.inspectBox)
        self.worstSimButton.setObjectName(_fromUtf8("worstSimButton"))
        self.simButtonGroup.addButton(self.worstSimButton)
        self.horizontalLayout_9.addWidget(self.worstSimButton)
        self.top5SimButton = QtGui.QRadioButton(self.inspectBox)
        self.top5SimButton.setObjectName(_fromUtf8("top5SimButton"))
        self.simButtonGroup.addButton(self.top5SimButton)
        self.horizontalLayout_9.addWidget(self.top5SimButton)
        self.bottom5SimButton = QtGui.QRadioButton(self.inspectBox)
        self.bottom5SimButton.setObjectName(_fromUtf8("bottom5SimButton"))
        self.simButtonGroup.addButton(self.bottom5SimButton)
        self.horizontalLayout_9.addWidget(self.bottom5SimButton)
        self.customSimButton = QtGui.QRadioButton(self.inspectBox)
        self.customSimButton.setObjectName(_fromUtf8("customSimButton"))
        self.simButtonGroup.addButton(self.customSimButton)
        self.horizontalLayout_9.addWidget(self.customSimButton)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem18)
        self.gridLayout_4.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.protectDefaultBox = QtGui.QCheckBox(self.inspectBox)
        self.protectDefaultBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.protectDefaultBox.setChecked(True)
        self.protectDefaultBox.setObjectName(_fromUtf8("protectDefaultBox"))
        self.gridLayout_4.addWidget(self.protectDefaultBox, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.simsLabel = QtGui.QLabel(self.inspectBox)
        self.simsLabel.setEnabled(False)
        self.simsLabel.setObjectName(_fromUtf8("simsLabel"))
        self.horizontalLayout_7.addWidget(self.simsLabel)
        self.simSelectEdit = QtGui.QLineEdit(self.inspectBox)
        self.simSelectEdit.setEnabled(False)
        self.simSelectEdit.setObjectName(_fromUtf8("simSelectEdit"))
        self.horizontalLayout_7.addWidget(self.simSelectEdit)
        self.simHelpLabel = QtGui.QLabel(self.inspectBox)
        self.simHelpLabel.setEnabled(False)
        self.simHelpLabel.setObjectName(_fromUtf8("simHelpLabel"))
        self.horizontalLayout_7.addWidget(self.simHelpLabel)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.simLoadButton = QtGui.QPushButton(self.inspectBox)
        self.simLoadButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.simLoadButton.sizePolicy().hasHeightForWidth())
        self.simLoadButton.setSizePolicy(sizePolicy)
        self.simLoadButton.setObjectName(_fromUtf8("simLoadButton"))
        self.horizontalLayout_7.addWidget(self.simLoadButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14.addWidget(self.inspectBox)
        spacerItem20 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem20)
        self.horizontalLayout_14.setStretch(0, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_14)
        self.dataBox = QtGui.QGroupBox(self.tab_results)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataBox.sizePolicy().hasHeightForWidth())
        self.dataBox.setSizePolicy(sizePolicy)
        self.dataBox.setMinimumSize(QtCore.QSize(0, 0))
        self.dataBox.setObjectName(_fromUtf8("dataBox"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.dataBox)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.dataTableLayout = QtGui.QHBoxLayout()
        self.dataTableLayout.setObjectName(_fromUtf8("dataTableLayout"))
        self.verticalLayout_9.addLayout(self.dataTableLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem21)
        self.dataExportButton = QtGui.QPushButton(self.dataBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataExportButton.sizePolicy().hasHeightForWidth())
        self.dataExportButton.setSizePolicy(sizePolicy)
        self.dataExportButton.setObjectName(_fromUtf8("dataExportButton"))
        self.horizontalLayout_8.addWidget(self.dataExportButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_9.setStretch(0, 10)
        self.verticalLayout_11.addWidget(self.dataBox)
        self.tabWidget.addTab(self.tab_results, _fromUtf8(""))
        self.tab_plots = QtGui.QWidget()
        self.tab_plots.setAutoFillBackground(True)
        self.tab_plots.setObjectName(_fromUtf8("tab_plots"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tab_plots)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.plotControlBox = QtGui.QGroupBox(self.tab_plots)
        self.plotControlBox.setMaximumSize(QtCore.QSize(600, 16777215))
        self.plotControlBox.setObjectName(_fromUtf8("plotControlBox"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.plotControlBox)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame = QtGui.QFrame(self.plotControlBox)
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.plotButton = QtGui.QPushButton(self.frame)
        self.plotButton.setObjectName(_fromUtf8("plotButton"))
        self.verticalLayout_10.addWidget(self.plotButton)
        self.plotExportButton = QtGui.QPushButton(self.frame)
        self.plotExportButton.setObjectName(_fromUtf8("plotExportButton"))
        self.verticalLayout_10.addWidget(self.plotExportButton)
        self.verticalLayout_12.addWidget(self.frame)
        spacerItem22 = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_12.addItem(spacerItem22)
        self.customSizeBox = QtGui.QCheckBox(self.plotControlBox)
        self.customSizeBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.customSizeBox.setObjectName(_fromUtf8("customSizeBox"))
        self.verticalLayout_12.addWidget(self.customSizeBox)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.customHeightSpinBox = QtGui.QDoubleSpinBox(self.plotControlBox)
        self.customHeightSpinBox.setEnabled(True)
        self.customHeightSpinBox.setObjectName(_fromUtf8("customHeightSpinBox"))
        self.gridLayout_2.addWidget(self.customHeightSpinBox, 1, 1, 1, 1)
        self.customHeightLabel = QtGui.QLabel(self.plotControlBox)
        self.customHeightLabel.setObjectName(_fromUtf8("customHeightLabel"))
        self.gridLayout_2.addWidget(self.customHeightLabel, 1, 0, 1, 1)
        self.customWidthSpinBox = QtGui.QDoubleSpinBox(self.plotControlBox)
        self.customWidthSpinBox.setEnabled(True)
        self.customWidthSpinBox.setObjectName(_fromUtf8("customWidthSpinBox"))
        self.gridLayout_2.addWidget(self.customWidthSpinBox, 0, 1, 1, 1)
        self.customWidthLabel = QtGui.QLabel(self.plotControlBox)
        self.customWidthLabel.setObjectName(_fromUtf8("customWidthLabel"))
        self.gridLayout_2.addWidget(self.customWidthLabel, 0, 0, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_2)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        self.line = QtGui.QFrame(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 0))
        self.line.setFrameShadow(QtGui.QFrame.Raised)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_11.addWidget(self.line)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.filterVarMinBox = QtGui.QCheckBox(self.plotControlBox)
        self.filterVarMinBox.setObjectName(_fromUtf8("filterVarMinBox"))
        self.horizontalLayout_22.addWidget(self.filterVarMinBox)
        self.filterVarMinLayout = QtGui.QHBoxLayout()
        self.filterVarMinLayout.setObjectName(_fromUtf8("filterVarMinLayout"))
        self.horizontalLayout_22.addLayout(self.filterVarMinLayout)
        self.filterVarMaxBox = QtGui.QCheckBox(self.plotControlBox)
        self.filterVarMaxBox.setObjectName(_fromUtf8("filterVarMaxBox"))
        self.horizontalLayout_22.addWidget(self.filterVarMaxBox)
        self.filterVarMaxLayout = QtGui.QHBoxLayout()
        self.filterVarMaxLayout.setObjectName(_fromUtf8("filterVarMaxLayout"))
        self.horizontalLayout_22.addLayout(self.filterVarMaxLayout)
        self.gridLayout.addLayout(self.horizontalLayout_22, 7, 1, 1, 1)
        self.xAxisLabel = QtGui.QLabel(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xAxisLabel.sizePolicy().hasHeightForWidth())
        self.xAxisLabel.setSizePolicy(sizePolicy)
        self.xAxisLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.xAxisLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xAxisLabel.setObjectName(_fromUtf8("xAxisLabel"))
        self.gridLayout.addWidget(self.xAxisLabel, 0, 0, 1, 1)
        self.xAxisVarBox = QtGui.QComboBox(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xAxisVarBox.sizePolicy().hasHeightForWidth())
        self.xAxisVarBox.setSizePolicy(sizePolicy)
        self.xAxisVarBox.setObjectName(_fromUtf8("xAxisVarBox"))
        self.gridLayout.addWidget(self.xAxisVarBox, 0, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.xAxisMinBox = QtGui.QCheckBox(self.plotControlBox)
        self.xAxisMinBox.setObjectName(_fromUtf8("xAxisMinBox"))
        self.horizontalLayout_15.addWidget(self.xAxisMinBox)
        self.xAxisMinLayout = QtGui.QHBoxLayout()
        self.xAxisMinLayout.setObjectName(_fromUtf8("xAxisMinLayout"))
        self.horizontalLayout_15.addLayout(self.xAxisMinLayout)
        self.xAxisMaxBox = QtGui.QCheckBox(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xAxisMaxBox.sizePolicy().hasHeightForWidth())
        self.xAxisMaxBox.setSizePolicy(sizePolicy)
        self.xAxisMaxBox.setObjectName(_fromUtf8("xAxisMaxBox"))
        self.horizontalLayout_15.addWidget(self.xAxisMaxBox)
        self.xAxisMaxLayout = QtGui.QHBoxLayout()
        self.xAxisMaxLayout.setObjectName(_fromUtf8("xAxisMaxLayout"))
        self.horizontalLayout_15.addLayout(self.xAxisMaxLayout)
        self.gridLayout.addLayout(self.horizontalLayout_15, 1, 1, 1, 1)
        self.yAxisLabel = QtGui.QLabel(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yAxisLabel.sizePolicy().hasHeightForWidth())
        self.yAxisLabel.setSizePolicy(sizePolicy)
        self.yAxisLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.yAxisLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yAxisLabel.setObjectName(_fromUtf8("yAxisLabel"))
        self.gridLayout.addWidget(self.yAxisLabel, 2, 0, 1, 1)
        self.yAxisVarBox = QtGui.QComboBox(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yAxisVarBox.sizePolicy().hasHeightForWidth())
        self.yAxisVarBox.setSizePolicy(sizePolicy)
        self.yAxisVarBox.setObjectName(_fromUtf8("yAxisVarBox"))
        self.gridLayout.addWidget(self.yAxisVarBox, 2, 1, 1, 1)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.yAxisMinBox = QtGui.QCheckBox(self.plotControlBox)
        self.yAxisMinBox.setObjectName(_fromUtf8("yAxisMinBox"))
        self.horizontalLayout_17.addWidget(self.yAxisMinBox)
        self.yAxisMinLayout = QtGui.QHBoxLayout()
        self.yAxisMinLayout.setObjectName(_fromUtf8("yAxisMinLayout"))
        self.horizontalLayout_17.addLayout(self.yAxisMinLayout)
        self.yAxisMaxBox = QtGui.QCheckBox(self.plotControlBox)
        self.yAxisMaxBox.setObjectName(_fromUtf8("yAxisMaxBox"))
        self.horizontalLayout_17.addWidget(self.yAxisMaxBox)
        self.yAxisMaxLayout = QtGui.QHBoxLayout()
        self.yAxisMaxLayout.setObjectName(_fromUtf8("yAxisMaxLayout"))
        self.horizontalLayout_17.addLayout(self.yAxisMaxLayout)
        self.gridLayout.addLayout(self.horizontalLayout_17, 3, 1, 1, 1)
        self.colorAxisLabel = QtGui.QLabel(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorAxisLabel.sizePolicy().hasHeightForWidth())
        self.colorAxisLabel.setSizePolicy(sizePolicy)
        self.colorAxisLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.colorAxisLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.colorAxisLabel.setObjectName(_fromUtf8("colorAxisLabel"))
        self.gridLayout.addWidget(self.colorAxisLabel, 4, 0, 1, 1)
        self.colorAxisVarBox = QtGui.QComboBox(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorAxisVarBox.sizePolicy().hasHeightForWidth())
        self.colorAxisVarBox.setSizePolicy(sizePolicy)
        self.colorAxisVarBox.setObjectName(_fromUtf8("colorAxisVarBox"))
        self.gridLayout.addWidget(self.colorAxisVarBox, 4, 1, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.colorAxisMinBox = QtGui.QCheckBox(self.plotControlBox)
        self.colorAxisMinBox.setObjectName(_fromUtf8("colorAxisMinBox"))
        self.horizontalLayout_21.addWidget(self.colorAxisMinBox)
        self.colorAxisMinLayout = QtGui.QHBoxLayout()
        self.colorAxisMinLayout.setObjectName(_fromUtf8("colorAxisMinLayout"))
        self.horizontalLayout_21.addLayout(self.colorAxisMinLayout)
        self.colorAxisMaxBox = QtGui.QCheckBox(self.plotControlBox)
        self.colorAxisMaxBox.setObjectName(_fromUtf8("colorAxisMaxBox"))
        self.horizontalLayout_21.addWidget(self.colorAxisMaxBox)
        self.colorAxisMaxLayout = QtGui.QHBoxLayout()
        self.colorAxisMaxLayout.setObjectName(_fromUtf8("colorAxisMaxLayout"))
        self.horizontalLayout_21.addLayout(self.colorAxisMaxLayout)
        self.gridLayout.addLayout(self.horizontalLayout_21, 5, 1, 1, 1)
        self.filterVarLabel = QtGui.QLabel(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterVarLabel.sizePolicy().hasHeightForWidth())
        self.filterVarLabel.setSizePolicy(sizePolicy)
        self.filterVarLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.filterVarLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.filterVarLabel.setObjectName(_fromUtf8("filterVarLabel"))
        self.gridLayout.addWidget(self.filterVarLabel, 6, 0, 1, 1)
        self.filterVarBox = QtGui.QComboBox(self.plotControlBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterVarBox.sizePolicy().hasHeightForWidth())
        self.filterVarBox.setSizePolicy(sizePolicy)
        self.filterVarBox.setObjectName(_fromUtf8("filterVarBox"))
        self.gridLayout.addWidget(self.filterVarBox, 6, 1, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addWidget(self.plotControlBox)
        spacerItem23 = QtGui.QSpacerItem(1, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem23)
        self.horizontalLayout_13.setStretch(0, 1)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.frame_2 = QtGui.QFrame(self.tab_plots)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.plotLayout = QtGui.QVBoxLayout()
        self.plotLayout.setMargin(6)
        self.plotLayout.setObjectName(_fromUtf8("plotLayout"))
        self.verticalLayout_14.addLayout(self.plotLayout)
        self.verticalLayout_15.addWidget(self.frame_2)
        self.verticalLayout_15.setStretch(1, 1)
        self.frame_2.raise_()
        self.tabWidget.addTab(self.tab_plots, _fromUtf8(""))
        self.tab_5_debug = QtGui.QWidget()
        self.tab_5_debug.setAutoFillBackground(True)
        self.tab_5_debug.setObjectName(_fromUtf8("tab_5_debug"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.tab_5_debug)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.importYAMLButton = QtGui.QPushButton(self.tab_5_debug)
        self.importYAMLButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.importYAMLButton.setObjectName(_fromUtf8("importYAMLButton"))
        self.horizontalLayout_19.addWidget(self.importYAMLButton)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem24)
        self.verticalLayout_18.addLayout(self.horizontalLayout_19)
        spacerItem25 = QtGui.QSpacerItem(20, 704, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem25)
        self.tabWidget.addTab(self.tab_5_debug, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(AdvancedPositionWidget)
        self.tabWidget.setCurrentIndex(0)
        self.maxResamplesComboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AdvancedPositionWidget)

    def retranslateUi(self, AdvancedPositionWidget):
        AdvancedPositionWidget.setWindowTitle(_translate("AdvancedPositionWidget", "Form", None))
        self.fileBox.setTitle(_translate("AdvancedPositionWidget", "File", None))
        self.importConfigButton.setText(_translate("AdvancedPositionWidget", "Import...", None))
        self.exportConfigButton.setText(_translate("AdvancedPositionWidget", "Export...", None))
        self.statusBox.setTitle(_translate("AdvancedPositionWidget", "Status", None))
        self.statusLabel.setText(_translate("AdvancedPositionWidget", "TextLabel", None))
        self.workDirBox.setTitle(_translate("AdvancedPositionWidget", "Worker directory", None))
        self.workDirLabel.setText(_translate("AdvancedPositionWidget", "Path", None))
        self.workDirToolButton.setText(_translate("AdvancedPositionWidget", "...", None))
        self.cleanDirCheckBox.setText(_translate("AdvancedPositionWidget", "Clean (allows restart, but will delete all previous results)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_config), _translate("AdvancedPositionWidget", "Control", None))
        self.objectiveBox.setTitle(_translate("AdvancedPositionWidget", "Objective", None))
        self.costVarLabel.setText(_translate("AdvancedPositionWidget", "Cost variable:", None))
        self.costVarCheckBox.setToolTip(_translate("AdvancedPositionWidget", "If checked, cost function is maximised. Otherwise, minimised.", None))
        self.costVarCheckBox.setText(_translate("AdvancedPositionWidget", "maximise", None))
        self.penaltyLabel.setText(_translate("AdvancedPositionWidget", "Penalty value:", None))
        self.penaltyUnitsLabel.setText(_translate("AdvancedPositionWidget", "TextLabel", None))
        self.toleranceLabel.setText(_translate("AdvancedPositionWidget", "Solution tolerance", None))
        self.toleranceUnitsLabel.setText(_translate("AdvancedPositionWidget", "TextLabel", None))
        self.computeBox.setTitle(_translate("AdvancedPositionWidget", "Compute", None))
        self.nThreadLabel.setText(_translate("AdvancedPositionWidget", "Number of threads:", None))
        self.threadInfoLabel.setText(_translate("AdvancedPositionWidget", "TextLabel", None))
        self.abortXLabel.setText(_translate("AdvancedPositionWidget", "Abort after x simulations:", None))
        self.abortXInfoabel.setText(_translate("AdvancedPositionWidget", "(0 implies no limit)", None))
        self.abortTimeLabel.setText(_translate("AdvancedPositionWidget", "Abort after time (in seconds):", None))
        self.abortTimeInfoabel.setText(_translate("AdvancedPositionWidget", "(0 implies no limit)", None))
        self.advancedBox.setTitle(_translate("AdvancedPositionWidget", "Advanced", None))
        self.minNoiseLabel.setText(_translate("AdvancedPositionWidget", "Minimum evaluations for noise handling:", None))
        self.minNoiseCheckBox.setText(_translate("AdvancedPositionWidget", "auto", None))
        self.maxNoiseLabel.setText(_translate("AdvancedPositionWidget", "Maximum evaluations for noise handling:", None))
        self.populationLabel.setText(_translate("AdvancedPositionWidget", "Optimiser population size:", None))
        self.populationCheckBox.setText(_translate("AdvancedPositionWidget", "auto", None))
        self.maxResamplesLabel1.setText(_translate("AdvancedPositionWidget", "Maximum resamples algorithm: ", None))
        self.maxResamplesComboBox.setItemText(0, _translate("AdvancedPositionWidget", "fixed", None))
        self.maxResamplesComboBox.setItemText(1, _translate("AdvancedPositionWidget", "auto", None))
        self.maxResamplesLabel2.setText(_translate("AdvancedPositionWidget", "Value:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("AdvancedPositionWidget", "Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_params), _translate("AdvancedPositionWidget", "Parameters", None))
        self.inspectBox.setTitle(_translate("AdvancedPositionWidget", "Inspect", None))
        self.inspectLabel.setText(_translate("AdvancedPositionWidget", "Select simulations to inspect:", None))
        self.deleteSimsBox.setText(_translate("AdvancedPositionWidget", "Delete existing simulations", None))
        self.bestSimButton.setText(_translate("AdvancedPositionWidget", "Best", None))
        self.worstSimButton.setText(_translate("AdvancedPositionWidget", "Worst", None))
        self.top5SimButton.setText(_translate("AdvancedPositionWidget", "Top 5", None))
        self.bottom5SimButton.setText(_translate("AdvancedPositionWidget", "Bottom 5", None))
        self.customSimButton.setText(_translate("AdvancedPositionWidget", "Custom", None))
        self.protectDefaultBox.setText(_translate("AdvancedPositionWidget", "Protect \'Default\' simulation", None))
        self.simsLabel.setText(_translate("AdvancedPositionWidget", "Simulations:", None))
        self.simHelpLabel.setText(_translate("AdvancedPositionWidget", "(separated by commas)", None))
        self.simLoadButton.setText(_translate("AdvancedPositionWidget", "Load", None))
        self.dataBox.setTitle(_translate("AdvancedPositionWidget", "Data", None))
        self.dataExportButton.setText(_translate("AdvancedPositionWidget", "Export...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_results), _translate("AdvancedPositionWidget", "Results", None))
        self.plotControlBox.setTitle(_translate("AdvancedPositionWidget", "Control", None))
        self.plotButton.setText(_translate("AdvancedPositionWidget", "Plot", None))
        self.plotExportButton.setText(_translate("AdvancedPositionWidget", "Export...", None))
        self.customSizeBox.setText(_translate("AdvancedPositionWidget", "Custom export\n"
"size (inches)", None))
        self.customHeightLabel.setText(_translate("AdvancedPositionWidget", "Height:", None))
        self.customWidthLabel.setText(_translate("AdvancedPositionWidget", "Width:", None))
        self.filterVarMinBox.setText(_translate("AdvancedPositionWidget", "Set min:", None))
        self.filterVarMaxBox.setText(_translate("AdvancedPositionWidget", "Set max:", None))
        self.xAxisLabel.setText(_translate("AdvancedPositionWidget", "x-axis variable:", None))
        self.xAxisMinBox.setText(_translate("AdvancedPositionWidget", "Set min:", None))
        self.xAxisMaxBox.setText(_translate("AdvancedPositionWidget", "Set max:", None))
        self.yAxisLabel.setText(_translate("AdvancedPositionWidget", "y-axis variable:", None))
        self.yAxisMinBox.setText(_translate("AdvancedPositionWidget", "Set min:", None))
        self.yAxisMaxBox.setText(_translate("AdvancedPositionWidget", "Set max:", None))
        self.colorAxisLabel.setText(_translate("AdvancedPositionWidget", "color-axis variable:", None))
        self.colorAxisMinBox.setText(_translate("AdvancedPositionWidget", "Set min:", None))
        self.colorAxisMaxBox.setText(_translate("AdvancedPositionWidget", "Set max:", None))
        self.filterVarLabel.setText(_translate("AdvancedPositionWidget", "filter variable:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_plots), _translate("AdvancedPositionWidget", "Plots", None))
        self.importYAMLButton.setToolTip(_translate("AdvancedPositionWidget", "Load simulation file (.yaml) from the working directory (without executing)", None))
        self.importYAMLButton.setText(_translate("AdvancedPositionWidget", "Import simulation file...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5_debug), _translate("AdvancedPositionWidget", "Debug", None))

