[tool.poetry]
name = "dtocean-app"
version = "2.1.1"
description = "Main graphical application for the DTOcean tools"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
readme = "README.md"
packages = [
  {include = "dtocean_app", from="src"},
  {include = "dtocean_plugins", from="src"},
]
include = [
  { path = "designer", format = ["sdist"] },
  { path = "src/dtocean_app/resources", format = ["sdist", "wheel"] },
  { path = 'src/dtocean_core/config/*.ini', format = ["sdist", "wheel"] },
  { path = 'src/dtocean_core/config/*.yaml', format = ["sdist", "wheel"] },
]

[tool.poetry.build]
script = "scripts/build-widgets.py"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
dtocean-core = {path = "../dtocean-core", develop = true}
dtocean-qt = {path = "../dtocean-qt", develop = true}
mdo-engine = {path = "../mdo-engine", develop = true}
polite-config = {path = "../polite-config", develop = true}
matplotlib = ">=3.8.4,<3.9"
numpy = ">=1.26.4,<2.0.0"
pandas = ">=2.2.3,<3.0.0"
shiboken6 = "^6.9.0"
pyside6 = "^6.9.0"
pillow = "^11.2.1"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
mock = "^5.1.0"
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
pytest-qt = "^4.4.0"
pytest-cov = "^6.0.0"

[tool.poetry.group.audit]
optional = true

[tool.poetry.group.audit.dependencies]
ruff = "^0.8.3"
pyright = "^1.1.396"
deptry = "^0.21.1"
pandas-stubs = "^2.2.3.241126"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '=='

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core", "pyside6"]
build-backend = "poetry.core.masonry.api"
