[tool.poetry]
name = "dtocean-app"
version = "2.1.1"
description = "Main graphical application for the DTOcean tools"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
readme = "README.md"
packages = [
  {include = "dtocean_app", from="src"}
  ]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
dtocean-core = {path = "../dtocean-core", develop = true}
polite-config = {path = "../polite-config", develop = true}
matplotlib = ">=3.8.4,<3.9"
numpy = ">=1.26.4,<2.0.0"
pandas = ">=2.2.3,<3.0.0"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-pinning-rule = '=='

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
