[tool.poetry]
name = "dtocean-environment"
version = "2.0.0"
description = "Environmental impact assessment module for the DTOcean tools"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
