[tool.poetry]
name = "mdo-engine"
version = "1.0.0"
description = "Data management, coupling and execution for MDO problems"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
license = "MIT"
readme = "README.md"
packages = [{include = "mdo_engine", from="src"}]
include = ['test/data/yaml/*.yaml']

[tool.poetry.scripts]
bootstrap-dds = 'mdo_engine.utilities.files:bootstrap_dds_interface'
xl-merge = 'mdo_engine.utilities.files:xl_merge_interface'

[tool.poetry.group.test]
optional = true

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.1.3"
openpyxl = "^3.1.5"
pandas = "^2.2.3"
pyyaml = "^6.0.2"
sqlalchemy = "^2.0.36"
xlrd = "^2.0.1"
xlwt = "^1.3.0"
polite-config = {path = "../polite-config"}
python-box = "^7.2.0"
pywin32 = {version = "^308", platform = "win32"}

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-mock = "^3.14.0"
mock = "^5.1.0"
dtocean-dummy-module = {path = "../dtocean-dummy-module"}
pytest-cov = "^6.0.0"

[tool.poetry-monorepo-dependency-plugin]
enable = true
version-pinning-strategy = "semver"

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
