[tool.poetry]
name = "dtocean-core"
version = "3.0.2"
description = "The main (non-graphical) interface for the DTOcean tools"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [{ include = "dtocean_core", from = "src" }]
include = [
  'src/dtocean_core/data/yaml/*.yaml',
  'src/dtocean_core/config/*.ini',
  'src/dtocean_core/config/*.yaml',
  'src/dtocean_core/strategies/position_optimiser/*.yaml',
]

[tool.poetry.scripts]
add-Te = 'dtocean_core.utils.hydrodynamics:add_Te_interface'
dtocean-core = 'dtocean_core.utils.execute:main_interface'
dtocean-core-config = 'dtocean_core.utils.config:init_config_interface'
dtocean-database = 'dtocean_core.utils.database:database_convert_interface'
_dtocean-optim-pos = 'dtocean_core.strategies.position_optimiser.iterator:interface'

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
mdo-engine = {path = "../mdo-engine", develop = true}
polite-config = {path = "../polite-config", develop = true}
cma = "^4.0.0"
contours = "^0.0.2"
cycler = "^0.12.1"
descartes = "^1.1.0"
geoalchemy2 = "^0.16.0"
matplotlib = "^3.8.4"
natsort = "^8.4.0"
netcdf4 = "^1.7.2"
numpy = "^1.26.4"
openpyxl = "^3.1.5"
pandas = "^2.2.3"
pillow = "^11.0.0"
psycopg = "^3.2.3"
pyproj = "^3.6.1"
pyshp = "^2.3.1"
python-dateutil = "^2.9.0.post0"
python-polylabel = "^0.6"
pyyaml = "^6.0.2"
ruamel-yaml-clib = "^0.2.12"
ruamel-yaml = "^0.18.6"
scipy = "^1.14.1"
shapely = "^2.0.6"
utm = "^0.7.0"
xarray = "^2024.11.0"
xlrd = "^2.0.1"
xlsxwriter = "^3.2.0"
xlwt = "^1.3.0"
basemap = "^1.4.1"

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-rewrite-rule = '=='

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
