[tool.poetry]
name = "dtocean-dummy-module"
version = "1.0.0"
description = "Dummy DTOcean module used in mdo-engine tests"
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
license = "GPL-3.0-or-later"
readme = "README.md"
packages = [{include = "dtocean_dummy", from="src"}]
include = ['*.ini', 'config/*.ini', 'config/*.yaml']

[tool.poetry.scripts]
dtocean-dummy = 'dtocean_dummy.command:module_interface'

[tool.poetry.group.test]
optional = true

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.1.3"
pandas = "^2.2.3"
openpyxl = "^3.1.5"
xlrd = "^2.0.1"
xlwt = "^1.3.0"
polite-config = {path = "../polite-config"}

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"

[tool.poetry-monorepo-dependency-plugin]
enable = true
version-pinning-strategy = "semver"

[tool.pyright]
typeCheckingMode = "basic"

[tool.ruff]
line-length = 80

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
