[tool.poetry]
name = "dtocean-data"
version = "2025.01.0"
description = "Fetches non-code files required by the DTOcean modules."
authors = ["Mathew Topper <damm_horse@yahoo.co.uk>"]
readme = "README.md"
packages = [
  { include = "dtocean_data", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
polite-config = {path = "../polite-config", develop = true}

[tool.poetry-monoranger-plugin]
enabled = true
monorepo-root = "../../"
version-rewrite-rule = '=='

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
