name: dtocean-hydrodynamics tests
on:
  push:
    branches:
      - main
    paths:
      - ".codecov.yml"
      - ".github/workflows/test-dtocean-hydrodynamics.yml"
      - "packages/dtocean-app/src/**"
      - "packages/dtocean-core/src/**"
      - "packages/dtocean-hydrodynamics/**"
      - "packages/polite-config/src/**"
      - "poetry.lock"
  pull_request:
    branches:
      - main
    paths:
      - ".codecov.yml"
      - ".github/workflows/test-dtocean-hydrodynamics.yml"
      - "packages/dtocean-app/src/**"
      - "packages/dtocean-core/src/**"
      - "packages/dtocean-hydrodynamics/**"
      - "packages/polite-config/src/**"
      - "poetry.lock"

jobs:
  pytest:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.14", "3.13", "3.12"]
    defaults:
      run:
        working-directory: packages/dtocean-hydrodynamics
    env:
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
          persist-credentials: false
      # https://github.com/actions/runner-images/issues/7048
      - name: Change Mirror Priorities (Linux)
        run: |
          sudo sed -i '/archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:2/priority:0/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/azure.archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:0/priority:1/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/security.ubuntu.com\/ubuntu\/\tpriority/ s/priority:3/priority:2/' /etc/apt/apt-mirrors.txt
          sudo cat /etc/apt/apt-mirrors.txt
        if: runner.os == 'Linux'
      - name: Install additional libraries (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libxkbcommon-x11-0 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 x11-utils
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
        if: runner.os == 'Linux'
      - name: Install package
        uses: ./.github/actions/poetry-install
        with:
          groups: '["dtocean-hydrodynamics", "test", "test-qt"]'
          python-version: ${{ matrix.python-version }}
      - name: Download large files
        run: |
          poetry run dtocean-hydro init
      - name: Run tests
        run: |
          poetry run pytest --no-gpu tests
  pytest-extras:
    name: Unit tests with plugins
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.14", "3.13", "3.12"]
    defaults:
      run:
        working-directory: packages/dtocean-hydrodynamics
    env:
      DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
          persist-credentials: false
      # https://github.com/actions/runner-images/issues/7048
      - name: Change Mirror Priorities (Linux)
        run: |
          sudo sed -i '/archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:2/priority:0/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/azure.archive.ubuntu.com\/ubuntu\/\tpriority/ s/priority:0/priority:1/' /etc/apt/apt-mirrors.txt
          sudo sed -i '/security.ubuntu.com\/ubuntu\/\tpriority/ s/priority:3/priority:2/' /etc/apt/apt-mirrors.txt
          sudo cat /etc/apt/apt-mirrors.txt
        if: runner.os == 'Linux'
      - name: Install additional libraries (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 libxkbcommon-x11-0 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 x11-utils
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
        if: runner.os == 'Linux'
      - name: Install package
        uses: ./.github/actions/poetry-install
        with:
          groups: '["dtocean-app", "dtocean-hydrodynamics", "test", "test-qt"]'
          python-version: ${{ matrix.python-version }}
      - name: Download large files
        run: |
          poetry run dtocean-hydro init
      - name: Run tests
        run: |
          poetry run pytest -v --cov src --cov-report=xml --no-gpu tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          flags: dtocean-hydrodynamics
  audit:
    name: Code audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/dtocean-hydrodynamics
    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true
          persist-credentials: false
      - name: Install package
        uses: ./.github/actions/poetry-install
        with:
          groups: '["audit", "dtocean-app", "dtocean-hydrodynamics"]'
          python-version: 3.14
      - name: Run ruff
        run: |
          poetry run ruff check --output-format github
      - name: Run pyright
        run: |
          poetry run pyright src
